[package]
name = "password_manager_rust"
version = "0.1.0"
authors = ["Blue Chalk <thebluechalk@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.5.5"
sha2 = "0.9.3"
rusqlite = "0.24.2"